version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
      - ./models:/app/models
    environment:
      - FLASK_ENV=development

  sqlite-web:
    image: coleifer/sqlite-web
    command: /app/scans.db --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
