services:
  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app         # auto-reload on code/template changes
      - ./models:/app/models
    environment:
      - FLASK_ENV=development
