services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: threat_scope
      MYSQL_USER: threat_user
      MYSQL_PASSWORD: threat_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
      - ./models:/app/models
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://threat_user:threat_password@mysql:3306/threat_scope
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
